config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homepages#index'

  resources :items, only: [:new, :create]
  get 'items/uploads', to: "items#uploads"
  get 'items/uploads', to: "items#uploads"
  get 'items/choose_form', to: "items#choose_form"
  get 'items/give_books', to: "items#give_books"
  get 'items/sell_books', to: "items#sell_books"
  post 'upload_image', to: "items#upload_image"  
  delete 'delete_image', to: "items#delete_image"
  get 'complete_register', to: "items#complete_register"

  resources :ks_platform, only: [:index, :show]
  resources :al_platform, only: [:index, :show]
  get "ks_platform_category", to: "ks_platform#category"
  get "al_platform_category", to: "al_platform#category"
  
  get "intrudaction", to: "items#intrudaction"
  get "ks_platform_search", to: "ks_platform#search"
  get "al_platform_search", to: "al_platform#search"
  
  get "contact", to: "contact#index"

end

app/controllers/ks_platform_controller.rb
class KsPlatformController < ApplicationController
  include KsPlatformHelper
  attr_accessor :categories, :cities

  def initialize
    @categories = Category.all
    @cities = ["Gjithë Kosovën","Artanë", "Besianë", "Burim", "Dardanë", "Deçan", "Dragash", "Drenas", "Ferizaj",
                "Fushë Kosovë", "Gjakovë", "Gjilan", "Kastriot", "Kaçanik", "Klinë", "Leposaviq", "Lipjan",
                "Malishevë", "Mitrovicë", "Pejë", "Prishtinë", "Prizren", "Rahovec", "Skenderaj", "Shtërpcë",
                "Shtime", "Therandë", "Viti", "Vushtrri", "Zubin", "Potok", "Zveçan"]
    @last_items = Item.where(country_id: 1, approve: true).last(4)
    super
  end

	def index
    @items = Item.where(country_id:1, approve: true).page params[:page] 
  end

  def show
    @item = Item.find(params[:id])
    @contact_result = nil

    if params[:code].present?
      @contact_result = check_code(params[:code], @item)
      if @contact_result == true
        regenerate_ks_code
      end
    end  
  end

  def category
    if params[:cat].present?
      @items = Category.find_by(name: params[:cat]).items.where(country_id: 1, approve: true).page params[:page]
    end
  end

  def search
    if params[:search] && params[:search] != ""
      @items = Item.where(country_id: 1, approve: true).search(params[:search], params[:location]).order("created_at DESC").page params[:page]
    end

    if params[:cat].present?
      @items = Category.find_by(name: params[:cat]).items.where(country_id: 1, approve: true).page params[:page] 
    end

    if params[:city].present?
      if params[:city] == "Gjithë Kosovën"
        @items = Item.where(country_id:1, approve: true).page params[:page]  
      else
        @items = Item.where(location: params[:city], country_id: 1, approve: true).page params[:page] 
      end
    end
  end

end

app/helpers/ks_platform_helper.rb
module KsPlatformHelper
	
	def check_code(input_code, item)
		product = item
		real_code = AccessCode.first.ks_code
		if real_code == input_code
			desplay_valid_contact(product)
		else
			desplay_invalid_contact	
		end
	end

	def desplay_valid_contact(product)
		"<h3 class='text-center'> Numri kontaktues </h3><h5 class='text-center' style='color: blue'>#{product.phone}</h5>".html_safe
	end

	def desplay_invalid_contact
		"<h3 class='text-center' style='color:red'> Kodi nuk eshte i sakt </h3>".html_safe
	end

	def regenerate_ks_code

	end

end

app/views/ks_platform/_category_list.html.erb
<div class="row">
  <div class="titl_sec">
    <div class="col-lg-12">
      <h3 class="main_titl text-left">
      Kategorite
      </h3>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="categ_info">
    <div class="info_sec first">
      <% @categories.each do |category| %>
      <div class="col-md-8">
        <%= link_to ks_platform_category_path(cat: category.name) do %>
        <i class="fa fa-long-arrow-right"></i>
        <p class="infos"> <%= category.name %> <span> (<%= category.items.where(country_id: 1).length %>) </span> </p>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ks_platform/_products.html.erb
<!-- Featured Properties Section -->
<section id="feat_propty">
	<div class="container">
		<div class="row">
			<div class="titl_sec">
				<div class="col-xs-6">
					<h3 class="main_titl text-left">
						TË gjitha librat				
					</h3>
				</div>
				<div class="col-xs-6">
					</h3>
				</div>
				<div class="clearfix"></div>
			</div>
			<!-- Property 1 -->
			<div class="container">
				<div class="row">
					<!-- Properties Section -->
					<section id="feat_propty">
						<div class="container">
							<div class="row">
								<!-- Property listing 1 -->
							<% if @items.any? %>
								<% @items.each do |item| %>
									<div class="col-md-4">
										<div class="panel panel-default" style="margin-bottom: 20px;">
											<div class="panel-image">
											  <% unless item.images.first.nil? %>
													<%= image_tag item.images.first.avatar.url(:profile), class: "img-responsive img-hover" %>
												<% else %>
													<%= image_tag "no_image.jpg", class: "img-responsive img-hover", style: "height: 252px;"%>
												<% end %>
												<div class="img_hov_eff">
													<%= link_to "More details", ks_platform_path(item), class: "btn btn-default btn_trans" %>
												</div>
											</div>											
												<% if item.status == "sale" %>
													<div class="sal_labl">
														NË SHITJE
													</div>
												<% elsif item.status == "give"%>
												 <div class="sal_labl" style="background-color: #023956">
														LIBËR FALAS
													</div>
												<% end %>											
											<div class="panel-body">
												<div class="prop_feat">
													<p class="area"><i class="fa fa-map-marker" aria-hidden="true"></i><%= item.location %></p>
													<p class="bedrom"><i class="fa fa-home"></i><%= item.address %></p>
													<p class="bedrom"><i class="fa fa-phone" aria-hidden="true"></i><%= item.phone %></p>
												</div>
												<h3 class="sec_titl"><%= truncate(item.title,length: 30) %></h3>
												<p class="sec_desc" style="height: 50px;"><%= truncate(item.description,length: 90) %></p>
												<div class="panel_bottom">
													<div class="col-md-6">
														<% if item.status == "sale" %>
															<p class="price text-left"><%= number_with_precision(item.price, :precision => 2) %>€</p>
														<% else %>
															<p class="price text-left"> FALAS</p>
														<% end %>
													</div>
													<div class="col-md-6">
														<p class="readmore text-right"><%= item.name %></p>
													</div>
												</div>
											</div>
										</div>
									</div>
								<% end %>
							<% else %>
								<p class="text-center"> Nuk gjinder asnje produkt </p>
							<% end %>
							</div>
							<!-- /.row -->
							<div class="spacer-40"></div>
							<%= paginate @items %>
							<!-- Pagination -->
							<!-- <div class="pagin">
								<ul>
									<li> <a class="active" href="#"> 1 </a> </li>
									<li> <a href="#"> 2 </a> </li>
									<li> <a href="#"> 3 </a> </li>
									<li> <a href="#"> 4 </a> </li>
									<li>
										<a href="#"> <i class="fa fa-long-arrow-right"></i> </a>
									</li>
								</ul>
							</div> -->
						</div>
						<!-- /.container -->
					</section>
					<div class="spacer-60"></div>
				</div>
			</div>
		</div>
		<!-- /.container -->
	</section>









	
	<%# if params[:search].present? %>
	<!-- Kerkuar: <%# params[:search] %><br><br> -->
	<%# end %>
	<%# if params[:cat].present? %>
	<!-- Kategoria: <%# params[:cat] %><br><br> -->
	<%# end %>
	<%# if @items.any? %>
	<%# @items.each do |item| %>
	<!-- 	<div class="col-md-4 col-sm-5">
			<div class="panel panel-default text-center" style="height: 300px;">
					<div class="panel-heading">
							<%# image_tag item.avatar.url, style: "width:180px;height:130px;" %>
					</div>
					<div class="panel-body">
							<h4><%# link_to item.title, ks_platform_path(item) %></h4>
							<p><%# item.description %></p>
							<a href="#" class="btn btn-primary">Shiko</a>
					</div>
			</div>
	</div> -->
	<%# end %>
	<!-- 	<div class="container" style="text-align: center">
			<%# paginate @items %>
	</div> -->
	<%# else %>
	<!-- "Nuk gjinder asnje produkt" -->
	<%# end %>

app/views/ks_platform/category.html.erb
<header class="bread_crumb">
  <div class="pg_links">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p class="lnk_pag"><a href="index.html"> Ballina </a> </p>
          <p class="lnk_pag"> / </p>
          <p class="lnk_pag"> Kategorite </p>
        </div>
        <div class="col-md-6 text-right">
          <p class="lnk_pag">
            <%= link_to "Kthehu te ballina" , root_path %>
          </p>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="spacer-60"></div>
<div class="container">
  <div class="row">
    <!-- Agent Section -->
    <section id="agent_sec" class="col-md-8">
      <!-- Property Listing -->
      <div class="row prlist_sec">
        <div class="titl_sec">
          <div class="col-lg-12">
            <h3 class="main_titl text-left">
            <% if params[:search].present? %>
            Kerkuar: <%= params[:search] %>
            <% elsif params[:cat].present? %>
            Kategoria: <%= params[:cat] %>
            <% elsif params[:city].present? %>
            Vendi: <%= params[:city] %>
            <% else %>
            Search/Category
            <% end %>
            </h3>
          </div>
          <div class="clearfix"></div>
        </div>
        <!-- Property List 1 -->
        <% if @items.any? %>
        <% @items.each do |item| %>
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-image">
              <% unless item.images.first.nil? %>
              <%= image_tag item.images.first.avatar.url(:profile), class: "img-responsive img-hover" %>
              <% else %>
              <%= image_tag "no_image.jpg", class: "img-responsive img-hover", style: "height: 252px;"%>
              <% end %>
              <div class="img_hov_eff">
                <%= link_to "More details", ks_platform_path(item), class: "btn btn-default btn_trans" %>
              </div>
            </div>
            <div class="sal_labl">
              For Sale
            </div>
            <div class="panel-body">
              <div class="prop_feat">
                <p class="area"><i class="fa fa-map-marker" aria-hidden="true"></i> <%= item.location %></p>
                <p class="bedrom"><i class="fa fa-home"></i><%= item.address %></p>
                <p class="bedrom"><i class="fa fa-phone" aria-hidden="true"></i><%= item.phone %></p>
              </div>
              <h3 class="sec_titl"><%= truncate(item.title, length: 30) %></h3>
              <p class="sec_desc" style="height: 50px;"><%= truncate(item.description,length: 90) %></p>
              <div class="panel_bottom">
                <div class="col-md-6">
                  <p class="price text-left"><%= number_with_precision(item.price, :precision => 2) %>€</p>
                </div>
                <div class="col-md-6">
                  <p class="readmore text-right"><%= item.name %></p>
                </div>
              </div>
            </div>
          </div>
          <div class="spacer-20"></div>
        </div>
        <% end %>
        <% else %>
        <p class="text-center"> Nuk gjindet asnje produkt </p>
        <% end %>
      </div>
      <%= paginate @items %>
      <!-- /.row -->
    </section>
    <!-- Sidebar Section -->
    <section id="sidebar" class="col-md-4">
      <!-- Categories -->
      <%= render "category_list" %>
      <!-- /.row -->
      <div class="spacer-30"></div>
      <!-- Featured Properties -->
      <div class="row">
        <div class="titl_sec">
          <div class="col-lg-12">
            <h3 class="main_titl text-left">
              Librat tjere
            </h3>
          </div>
          <div class="clearfix"></div>
        </div>
        <% @last_items.each do |la_item| %>
        <div class="side_feat">
          <div class="panel panel-default">
            <div class="panel-image col-md-3">
              <% unless la_item.images.first.nil? %>
              <%= image_tag la_item.images.first.avatar.url, class: "img-responsive img-hover" %>
              <% else %>
              <%= image_tag "no_image.jpg", class: "img-responsive img-hover" %>
              <% end %>
            </div>
            <div class="panel-body col-md-9">
              <h3 class="sec_titl">
              <%= link_to la_item.title, ks_platform_path(la_item) %>
              </h3>
              <div class="prop_feat">
                <p class="area"><i class="fa fa-home"></i><%= la_item.location %></p>
                <p class="bedrom"><i class="fa fa-phone" aria-hidden="true"></i><%= la_item.phone %></p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <!-- /.row -->
      <div class="spacer-30"></div>
    </section>
    <div class="spacer-60"></div>
  </div>
</div>

app/views/ks_platform/index.html.erb
<!-- Header Stat Banner -->
<header id="banner" class="stat_bann">
  <div class="bannr_sec">
    <%= image_tag 'books.jpg' %>
    <h1 class="main_titl">
      Nxeje Karrigen
    </h1>
    <h4 class="sub_titl">
     Publiko libra te ndryshem
    </h4>
  </div>
</header>
<section id="srch_slide">
  <div class="container" >
    <!-- Search & Slider -->
    <div class="row">
      <!-- Search Form -->
      <div class="col-md-4">
        <div class="srch_frm"  style="width: 800px;margin-left: 160px;">
          <%= form_tag(ks_platform_search_path, :method => "get") do %>
          <div class="control-group form-group col-md-6">
            <div class="controls">
              <%= text_field_tag :search, params[:search], class: "form-control", :placeholder => "KËRKO ..", required: true  %>
              <p class="help-block"></p>
            </div>
          </div>
          <div class="control-group form-group col-md-4">
            <div class="controls">
              <%= select_tag :location, options_for_select(@cities), class: "form-control", required: true %>
            </div>
          </div>
          <div id="success" class="col-md-2"></div>
          <!-- For success/fail messages -->
          <%= button_tag class: "btn btn-primary", style: "margin-top: -1px;" do %>
          <i class="glyphicon glyphicon-search"></i> KËRKO
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>
<div class="spacer-60"></div>
<%= render "products" %>

app/views/ks_platform/search.html.erb
<header class="bread_crumb">
  <div class="pg_links">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p class="lnk_pag"><a href="index.html"> Ballina </a> </p>
          <p class="lnk_pag"> / </p>
          <p class="lnk_pag"> Kerkimi </p>
        </div>
        <div class="col-md-6 text-right">
          <p class="lnk_pag">
            <%= link_to "Kthehu te ballina" , root_path %>
          </p>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="spacer-60"></div>
<div class="container">
  <div class="row">
    <!-- Agent Section -->
    <section id="agent_sec" class="col-md-8">
      <!-- Property Listing -->
      <div class="row prlist_sec">
        <div class="titl_sec">
          <div class="col-lg-12">
            <h3 class="main_titl text-left">
            <% if params[:search].present? %>
            Kerkuar: <%= params[:search] %>
            <% elsif params[:cat].present? %>
            Kategoria: <%= params[:cat] %>
            <% elsif params[:city].present? %>
            Vendi: <%= params[:city] %>
            <% else %>
            Search/Category
            <% end %>
            </h3>
          </div>
          <div class="clearfix"></div>
        </div>
        <!-- Property List 1 -->
        <% if @items.any? %>
        <% @items.each do |item| %>
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-image">
              <% unless item.images.first.nil? %>
              <%= image_tag item.images.first.avatar.url, class: "img-responsive img-hover", style: "height: 250px;"%>
              <% else %>
              <%= image_tag "no_image.jpg", class: "img-responsive img-hover", style: "height: 250px;"%>
              <% end %>
              <div class="img_hov_eff">
                <%= link_to "More details", ks_platform_path(item), class: "btn btn-default btn_trans" %>
              </div>
            </div>
            <% if item.status == "sale" %>
              <div class="sal_labl">
                NË SHITJE
              </div>
            <% elsif item.status == "give"%>
             <div class="sal_labl" style="background-color: #023956">
                LIBËR FALAS
              </div>
            <% end %> 
            <div class="panel-body">
              <div class="prop_feat">
                <p class="area"><i class="fa fa-map-marker" aria-hidden="true"></i> <%= item.location %></p>
                <p class="bedrom"><i class="fa fa-home"></i><%= item.address %></p>
                <p class="bedrom"><i class="fa fa-phone" aria-hidden="true"></i><%= item.phone %></p>
              </div>
              <h3 class="sec_titl"><%= item.title %></h3>
              <p class="sec_desc" style="height: 50px;"><%= truncate(item.description,length: 90) %></p>
              <div class="panel_bottom">
                <div class="col-md-6">
                  <p class="price text-left"><%= number_with_precision(item.price, :precision => 2) %>€</p>
                </div>
                <div class="col-md-6">
                  <p class="readmore text-right"><%= item.name %></p>
                </div>
              </div>
            </div>
          </div>
          <div class="spacer-20"></div>
        </div>
        <% end %>
        <% else %>
        <p class="text-center"> Nuk gjindet asnje produkt </p>
        <% end %>
      </div>
      <%= paginate @items %>
      <!-- /.row -->
    </section>
    <!-- Sidebar Section -->
    <section id="sidebar" class="col-md-4">
      <!-- Search Form -->
      <div class="row">
        <div class="col-md-12">
          <div class="srch_frm">
            <h3>KËRKO</h3>
            <%= form_tag(ks_platform_search_path, :method => "get") do %>
            <div class="control-group form-group">
              <div class="controls">
                <%= text_field_tag :search, params[:search], class: "form-control", :placeholder => "Kerko libra ..", required: true  %>
                <p class="help-block"></p>
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <%= select_tag :location, options_for_select(@cities), class: "form-control", :include_blank => "Zgjedh lokacionin", required: true %>
              </div>
            </div>
            <div id="success4"></div>
            <!-- For success/fail messages -->
            <button type="submit" class="btn btn-primary">KËRKO</button>
            <% end %>
          </div>
        </div>
      </div>
      <!-- /.row -->
      <div class="spacer-30"></div>
      <!-- Categories -->
      <%= render "category_list" %>
      <!-- /.row -->
      <div class="spacer-30"></div>
      <!-- Featured Properties -->
      <div class="row">
        <div class="titl_sec">
          <div class="col-lg-12">
            <h3 class="main_titl text-left">
              Librat tjere
            </h3>
          </div>
          <div class="clearfix"></div>
        </div>
        <% @last_items.each do |la_item| %>
        <div class="side_feat">
          <div class="panel panel-default">
            <div class="panel-image col-md-3">
              <% unless la_item.images.first.nil? %>
              <%= image_tag la_item.images.first.avatar.url, class: "img-responsive img-hover" %>
              <% else %>
              <%= image_tag "no_image.jpg", class: "img-responsive img-hover" %>
              <% end %>
            </div>
            <div class="panel-body col-md-9">
              <h3 class="sec_titl">
              <%= link_to la_item.title, ks_platform_path(la_item) %>
              </h3>
              <div class="prop_feat">
                <p class="area"><i class="fa fa-home"></i><%= la_item.location %></p>
                <p class="bedrom"><i class="fa fa-phone" aria-hidden="true"></i><%= la_item.phone %></p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <!-- /.row -->
      <div class="spacer-30"></div>
      <!-- Tags -->
      <div class="row">
        <div class="titl_sec">
          <div class="col-lg-12">
            <h3 class="main_titl text-left">
            Qytetet
            </h3>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="tags_sec">
          <% @cities.each do |c| %>
          <div class="tags_box">
            <%= link_to c, ks_platform_search_path(city: c) %>
          </div>
          <% end %>
        </div>
      </div>
      <!-- /.row -->
      <div class="spacer-30"></div>
    </section>
    <div class="spacer-60"></div>
  </div>
</div>

app/views/ks_platform/show.html.erb
<div class="spacer-30"></div>
<div class="container">
  <div class="row">
    <div class="titl_sec">
      <div class="col-xs-6">
        <h3 class="main_titl text-left" style="margin-right: 20px;">        
          Profili i librit       
        </h3>
      </div>
      <div class="col-xs-6">
        </h3>
      </div>
      <div class="clearfix"></div>
    </div>
    <!-- Proerty Details Section -->
    <section id="prop_detal" class="col-md-8">
      <div class="row">
        <div class="panel panel-default" style="">
          <!-- Proerty Slider Images -->
          <div class="panel-image">
            <ul id="prop_slid">
              <% unless @item.images.first.nil? %>
              <% @item.images.each do |image| %>
              <li>
                <%= image_tag image.avatar.url(:medium), class: "img-responsive", alt: "Property Slide Image" %>
              </li>
              <% end %>
              <% end %>
            </ul>
            <!-- Proerty Slider Thumbnails -->
            <br>
            <div class="col-md-12 rel_img">
              <ul id="slid_nav">
                <% n = 0 %>
                <% unless @item.images.first.nil? %>
                <% @item.images.each do |image| %>
                <li>
                  <a data-slide-index="<%= n %>" href="">
                    <%= image_tag image.avatar.url(:thumb), class: "img-responsive"  %>
                    <% n = n + 1 %>
                  </a>
                </li>
                <% end %>
                <% end %>
              </ul>
            </div>
            <div class="clearfix"></div>
          </div>
          <br>
          <div class="panel-body">
            <div class="prop_feat">
              <p class="area"><i class="fa fa-globe" aria-hidden="true"></i><%= @item.country.name %></p>
              <p class="area"><i class="fa fa-home"></i><%= @item.location %></p>
              <p class="area"><i class="fa fa-map-marker" aria-hidden="true"></i><%= @item.address %></p>
              <p class="bedrom"><i class="fa fa-bed"></i><%= @item.category.name %></p>
            </div>
            <h3 class="sec_titl">
              <%= @item.title %>             
            </h3>
            
            <p class="sec_desc">
              <%= @item.description %>
            </p>     

            <div class="col_labls larg_labl">
              <p class="or_labl">Telefoni: <%= @item.phone %></p>
              <% if @item.status == "sale" %>
                <p class="blu_labl"><%= number_with_precision(@item.price, :precision => 2) %> €</p>
              <% elsif @item.status == "give" %>
                <p class="blu_labl">FALAS</p>
              <% end %>

            </div>       
            <!-- Proerty Additional Info -->

          </div>
        </div>
      </div>
      <!-- /.row -->
      <div class="spacer-30"></div>
      
    </section>
    <!-- Sidebar Section -->
    <section id="sidebar" class="col-md-4">
      <!-- Search Form -->
      <div class="row">
        <div class="col-md-12">
          <div class="srch_frm">
            <h3>KËRKO</h3>
            <%= form_tag(ks_platform_search_path, :method => "get") do %>
            <div class="control-group form-group">
              <div class="controls">
                <%= text_field_tag :search, params[:search], class: "form-control", :placeholder => "Kerko libra ..", required: true  %>
                <p class="help-block"></p>
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <%= select_tag :location, options_for_select(@cities), class: "form-control", :include_blank => "Zgjedh lokacionin", required: true %>
              </div>
            </div>
            <div id="success4"></div>
            <!-- For success/fail messages -->
            <button type="submit" class="btn btn-primary">KËRKO</button>
            <% end %>
          </div>
        </div>
      </div>
      <!-- /.row -->
      <div class="spacer-30"></div>
      <!-- Categories -->
      <%= render "category_list" %>
    </section>
    <div class="spacer-60"></div>
  </div>
</div>
<%= javascript_include_tag 'jquery', 'data-turbolinks-track' => false %>