config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homepages#index'

  resources :items, only: [:new, :create]
  get 'items/uploads', to: "items#uploads"
  get 'items/uploads', to: "items#uploads"
  get 'items/choose_form', to: "items#choose_form"
  get 'items/give_books', to: "items#give_books"
  get 'items/sell_books', to: "items#sell_books"
  post 'upload_image', to: "items#upload_image"  
  delete 'delete_image', to: "items#delete_image"
  get 'complete_register', to: "items#complete_register"

  resources :ks_platform, only: [:index, :show]
  resources :al_platform, only: [:index, :show]
  get "ks_platform_category", to: "ks_platform#category"
  get "al_platform_category", to: "al_platform#category"
  
  get "intrudaction", to: "items#intrudaction"
  get "ks_platform_search", to: "ks_platform#search"
  get "al_platform_search", to: "al_platform#search"
  
  get "contact", to: "contact#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  
  # extend FriendlyId
  # friendly_id :name, use: :slugged

  paginates_per 16
  
	has_attached_file :avatar, styles: { medium: "250x250#", thumb: "54x54#", profile: '386x244#' }, :default_url => 'no_image.jpg'
	validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	belongs_to :category
  belongs_to :country
  has_many :images
  
  validates :name, presence: true
  validates :title, presence: true
  validates :title, uniqueness: { :message => 'Titulli eshte i njejte (provo nje titull tjeter)'}
  validates :description, presence: true
  validates :phone, presence: { :message => 'Numri i telefonit eshte i njejte'}
  validates :category, presence: true
  validates :country, presence: true
  validates :location, presence: true

  def self.search(search, location)
    
    if location == "Gjithë Kosovën" || location == "Gjithë Shqiperinë"
      where("title iLIKE ? OR description LIKE ?", "%#{search}%","%#{search}%") 
    else
      where("AND title iLIKE ? OR description LIKE ?","%#{search}%","%#{search}%")
      where(location: location)
    end
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ItemsHelper
  before_action :check_item_status, only: [:new]
  before_action :check_upload_status, only: [:uploads]
  before_action :check_choose_form, only: [:choose_form]
  $item_id ||= nil
  $item_status ||= nil
  $form_status ||= nil
  $code_status ||= nil

  def new
    @items = Item.new
  end

  def create 
    @item = Item.new(require_params.merge!({status: "give"})) if $form_status == "give"
    @item = Item.new(require_params.merge!({status: "sale"})) if $form_status == "sale"
    if @item.save
      flash[:success] = "Kerkesa juaj eshte bere me sukses"
      $item_id = @item.id
      $item_status = "between complete"
      redirect_to items_uploads_url
    else
      flash[:danger] = @item.errors.messages
      redirect_to new_item_path    
    end
  end

  def uploads
    @image_content = Item.find_by(id: $item_id).images    
  end

  def upload_image    
    @item_image = Image.create(item_id: $item_id, avatar: params[:file])
    if @item_image.save!
      render json: { image: @item_image, url:@item_image.avatar.url(:profile)}
    else
      puts 'Hello'
      render json: { error: 'Failed to process' }, status: 422
    end    
  end

  def delete_image
    Image.where(id: params[:image_content]).destroy_all
    redirect_to items_uploads_url
  end

  def complete_register
    $item_id = nil
    $item_status = nil
    $form_status = nil
    $code_status = nil
    flash[:success] = "Kerkesa juaj eshte bere me sukses"
    redirect_to items_choose_form_path
  end

  def choose_form
  end

  def give_books
    $form_status = "give"
    redirect_to new_item_path
  end

  def sell_books
    $form_status = "sale"
    unless $code_status == true
      if check_code(params[:code]) == true
        $code_status = true
        redirect_to new_item_path   
      else
        redirect_to items_choose_form_path
        flash[:error] = "Kodi nuk eshte valid"
      end   
    else
      redirect_to new_item_path 
    end 
  end

  private 

  def require_params
    params.require(:item).permit(:name, :email, :address, :location, :phone, :country_id, :category_id, :title, :description, :avatar, :price)
  end

  def check_item_status
    if $item_status == "between complete"
      redirect_to items_uploads_url
    end
    if $form_status == nil
      redirect_to items_choose_form_path
    end
  end

  def check_upload_status
    if $item_status == "between complete"
    elsif
      redirect_to new_item_path
   end
  end

  def check_choose_form
    if $item_status == "between complete"
      redirect_to items_uploads_url
    else
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
	def check_code(input_code)
		code_form = input_code
		real_code = AccessCode.first.registration_code
		if real_code == input_code
			true
		else
			false	
		end
	end

	def regeneration_code
		real_code = AccessCode.first
		real_code.registration_code = rand(36**6).to_s(36)
		real_code.save
	end
end

app/views/items/_errors.html.erb
<% if flash[:danger].present? %>
  <div style="background-color: #ef7351;padding: 15px;border-radius: 5px;">
  	<div class="col-md-2"></div>
  	
   	<div class="row">
      <% flash[:danger].each do |colmun, message| %>
        <p style="color: white"><i class="fa fa-exclamation" aria-hidden="true"></i> <%= colmun %>: <%= message[0] %></p>
      <% end %>
    </div>
  </div>
<% end %>
<% if flash[:success].present? %>
  <div style="background-color: #3EA186;padding: 15px;border-radius: 5px;">
  	<div class="col-md-2"></div>
  	<div class="row">
      <p style="color: white"><i class="fa fa-check" aria-hidden="true"></i> <%= flash[:success] %></p>     
    </div>
  </div>
<% end %>
<% if flash[:error].present? %>
  <div style="background-color: #ef7351;padding: 15px;border-radius: 5px;">
    <div class="col-md-2"></div>
    <div class="row">
      <p style="color: white"><i class="fa fa-exclamation" aria-hidden="true"></i> <%= flash[:error] %></p>     
    </div>
  </div>
<% end %>
<br>

app/views/items/_give_books.html.erb
<div class="container" id="div2" style="width: 950px;">
	<div class="modal-content"> 
		<div class="modal-header" style="margin-left: 100px;">
			<form>
	    	<div class="col-xs-8">
			  	Faleminderit per kontributin tuaj vazhdo me regjistrimin e librave
			  </div>
			  <div class="col-xs-4">
			  	<div >	
				  	<%= link_to items_give_books_path, class: "btn btn-info" do %>
				  		Vazhdo regjistrimin <i class="fa fa-arrow-right" aria-hidden="true"></i>
				  	<% end %>			       
				  </div>
			  </div>
			</form>
	  </div>	

	  </div> 
</div>

app/views/items/_products.html.erb
<% if params[:search].present? %>
	Kerkuar: <%= params[:search] %><br><br>
<% end %>

<% if @items.any? %>
	<% @items.each do |item| %>
	<div class="col-md-3 col-sm-6">
		<div class="panel panel-default text-center" style="height: 300px;">
			<div class="panel-heading">
				<%= image_tag item.avatar.url, style: "width:200px;height:130px;" %>
			</div>
			<div class="panel-body">
				<h4><%= link_to item.title, item_path(item) %></h4>
				<p><%= item.description %></p>
				<a href="#" class="btn btn-primary">Shiko</a>
			</div>
		</div>
	</div>
	<% end %>
	<div class="container" style="text-align: center">
		<%= paginate @items %>
	</div>
<% else %>
	"Nuk gjinder asnje produkt"
<% end %>

app/views/items/_sell_books.html.erb
<div class="container" id="div1" style="width: 950px;">
	<div class="modal-content">
		
		<div class="modal-header">
			<h4 class="modal-title">Mundesia per regjistrim</h4>
		</div>
		<div class="modal-body">
			<div class="row">
				<div class="col-md-12 text-center" style="border-bottom: 1px solid brown">
					<p>Manuali se si duhet vepruar per pranimin e kodit <br>
						Posht shihen dy menyrat per Kosove dhe Shqiperi ndiqni hapat ne vijim <br>
						Pasi te keni perfunduar hapat ne vijin ne numrin tuaj te telefonit do te ju dergohet nje kode <br>
					me te cilin mund te beni regjistrimin tuaj.</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 text-center" style="border-right: 1px solid brown">
					<h3> Kosove </h3><br>
					<h4><%= image_tag "vala.png", style: "width: 200px;height: 130px;" %></h5><br>
					<p style="text-align: center;border-bottom: 1px solid #a9bcca">Instrukcionet për të transferuar kredine prej kontos së juaj me parapagim në një konto tjetër me parapagim: <br><br>Shtypni si në vijim: <b style="color:red"> *121*44xxxxxx*1*00000# </b> dhe konfirmojeni duke shtypur butonin për thirrje.</p><br>
					<p style="color: red;background-color: #a9c3db">Pasi transaksioni te jete kryer me sukses ne numrin e sakte do te pranoni kodin per regjistrim</p>
				</div>
				<div class="col-md-6 text-center">
					<h3> Shqiperi </h3><br>
					<h5>Vodafone</h5><br>
					<p style="text-align: center"><b style="color:green">http://www.vodafone.al/ </b></p><br>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<%= form_tag items_sell_books_path, method: :get do %>
				<div class="col-md-12">
				 	<% unless $code_status == true %>
				  		<%= text_field_tag :code, "",class: 'form-control pull-right', style: "width:180px;", placeholder: "Shkruani kodin*", required: true  %>
				  	<% end %>
				  </div>
				  <div class="col-md-12" style="margin-top: 15px;">
				  	<%= button_tag(type: 'submit', class: "btn btn-info pull-right") do %>
								Vazhdo regjistrimin <i class="fa fa-arrow-right" aria-hidden="true"></i>
					<% end %>
				</div>				
			<% end %>
		</div>
	</div>
</div>

app/views/items/choose_form.html.erb
<br>
<div class="container">
	<div class="row">
		<div class="titl_sec">
			<div class="col-xs-6">
				<h3 class="main_titl text-left" style="margin-right: 20px;">
				Lloji i regjistrimit
				</h3>
				
			</div>
			<div class="col-xs-6">
				</h3>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<div class="container" style="width: 950px;">
	<div class="modal-content">
		<div class="modal-header" style="margin-left: 100px;">
			<form>
				<div class="col-xs-6">
					<input type="checkbox" id="give_books" name="value1" value="give" /> Deshiroj te dhuroj libera
				</div>
				<div class="col-xs-6">
					<input type="checkbox" id="sell_books" name="value1" value="sell" /> Deshiroj te shes libera
				</div>
			</form>
		</div>
	</div>
	<br>
	<%= render 'errors' %>
</div>




<%= render "give_books" %>
<%= render "sell_books" %>


<script type="text/javascript">

	setTimeout(function(){
		$('.footer').css('position', "absolute");
	   if ( $('#give_books').is(':checked') ){
	    $('#div2').show();
	  }
	  else {
	    $('#div2').hide();
	  }
	  if ( $('#sell_books').is(':checked') ){
	    $('#div1').show();
	  }
	  else {
	    $('#div1').hide();
	  }
	}, 1)


	$('#give_books').change(function () {
	    if ($(this).is(':checked')) {
	     $('#div2').fadeIn(100);
	     $('#div1').fadeOut(100)
	     $('.footer').css('position', "absolute");
	    }
	    else {
	      $('#div2').fadeOut(100);
	    }
	});
	$('#sell_books').change(function () {
	    if ($(this).is(':checked')) {
	     $('#div1').fadeIn(100);
	     $('#div2').fadeOut(100);
	     $('.footer').css('position', "relative");
	    }
	    else {
	      $('#div1').fadeOut(100);
	       $('.footer').css('position', "absolute");
	    }
	});

	$("input:checkbox").on('click', function() {
	  // in the handler, 'this' refers to the box clicked on
	  var $box = $(this);
	  if ($box.is(":checked")) {
	    // the name of the box is retrieved using the .attr() method
	    // as it is assumed and expected to be immutable
	    var group = "input:checkbox[name='" + $box.attr("name") + "']";
	    // the checked state of the group/box on the other hand will change
	    // and the current value is retrieved using .prop() method
	    $(group).prop("checked", false);
	    $box.prop("checked", true);
		  if ($('#sell_books').is(':not(:checked)')) {
	     $('#expire_date').hide();
	    }
	  }else {
	    $box.prop("checked", false);
	  }

	});
</script>

app/views/items/index.html.erb
<br><br>
<div class="container">
	<%= form_tag(items_path, :method => "get") do %>
		<div class="input-group col-md-8" style="margin-left: 180px;">
   	<%= text_field_tag :search, params[:search], placeholder: "Kerko libra ....", class: "form-control input-lg", requred: true  %>
		<span class="input-group-btn">
			<%= button_tag class: "btn btn-info btn-lg" do %>
				<i class="glyphicon glyphicon-search"></i>
			<% end %>
		</span>

	</div>
		<% end %>


	<div class="col-lg-12">
		<h4 class="page-header"><%= "Te gjitha librat".upcase %></h4>
	</div>
<%= render "products" %>
</div>

app/views/items/intrudaction.html.erb
<br><br>
<div class="container" style="width: 950px;">
	<div class="modal-content">
	  
		<div class="modal-header">
	    <h4 class="modal-title">Mundesia per regjistrim</h4>
	  </div>

	  <div class="modal-body">
	    <div class="row">
			  <div class="col-md-12 text-center" style="border-bottom: 1px solid brown">
			  	<p>Manuali se si duhet vepruar per pranimin e kodit <br>
			  	Posht shihen dy menyrat per Kosove dhe Shqiperi ndiqni hapat ne vijim <br>
			  	Pasi te keni perfunduar hapat ne vijin ne numrin tuaj te telefonit do te ju dergohet nje kode <br>
			  	me te cilin mund te beni regjistrimin tuaj.</p>
			  </div>
			</div>
			<div class="row">
			  <div class="col-md-6 text-center" style="border-right: 1px solid brown">
			  	<h3> Kosove </h3><br>
			  	<h4>Vala 900</h5><br>

			  	<p style="text-align: center;border-bottom: 1px solid #a9bcca">Instrukcionet për të transferuar kredine prej kontos së juaj me parapagim në një konto tjetër me parapagim: <br><br>Shtypni si në vijim: <b style="color:red"> *121*44xxxxxx*1*00000# </b> dhe konfirmojeni duke shtypur butonin për thirrje.<br><br> Do te merrni një porosi konfimimi për të autorizur këtë transfer. Nese informata është në rregull atëherë, konfirmojeni. Do të merrni prapë një porosi për transfer të kredisë me sukses.</p><br>

			  	<h4>IPKO</h5><br>

			  	<p style="text-align: center;border-bottom: 1px solid #a9bcca">Udhezimet për të transferuar kredine prej kontos tuaj me parapagim në një konto tjetër me parapagim:<br><br>
					Hapi 1:<br>
					Shtypni si në vijim: <b style="color:red">  *124*1*049xxxxxx# </b> dhe konfirmojeni duke shtypur butonin për thirrje.
					<br><br>Hapi 2:<br>
					Do të merrni një porosi konfirmimi për të autorizur këtë transfer. Nëse informata është në rregull atëherë,<br><br> konfirmojeni duke shkruar *124#. Do të merrni prapë një porosi për transfer të kredisë me sukses.
					</p><br>
			  	<p style="color: red;background-color: #a9c3db">Pasi transaksioni te jete kryer me sukses ne numrin e sakte do te pranoni kodin per regjistrim</p>
			  </div>
			  <div class="col-md-6 text-center">
			  <h3> Shqiperi </h3><br>
			  	<h5>Vodafone</h5><br>

			  	<p style="text-align: center"><b style="color:green">http://www.vodafone.al/ </b></p><br>
				</div>
			</div>
	  </div>

	  <div class="modal-footer">	
	  	<%= link_to new_item_path, class: "btn btn-info" do %>
	  		Vazhdo regjistrimin e librave tuaj >
	  	<% end %>			       
	  </div>

	</div>
</div>

app/views/items/new.html.erb
<br><br>
<div class="container">
	<div class="row">
		<div class="titl_sec">
			<div class="col-xs-6">
				<h3 class="main_titl text-left" style="margin-right: 20px;">
				Regjistro Librat
				</h3>
				<h3 class="main_titl text-left" style="border-bottom: none;width: 30px;">
				<i class="fa fa-arrow-right" aria-hidden="true"></i>
				</h3>
				<h3 class="main_titl text-left" style="border-bottom: none;">
				Galeria e fotografive
				</h3>
			</div>
			<div class="col-xs-6">
				</h3>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<div class="container" style="width: 900px;">
	<%= render 'errors' %>
	<div class="modal-content">
		<div class="modal-body">
			<div class="log_form">
				<%= form_for @items, url: { controller: "items", action: "create" } do |f| %>
				<div class="control-group form-group">
					<div class="controls">
						<%= f.text_field :name, placeholder: "Emri*", class: 'form-control', required: true %>
						<p class="help-block"></p>
					</div>
					<div class="controls">
						<%= f.text_field :email, placeholder: "Email", class: 'form-control' %>
						<p class="help-block"></p>
					</div>
				</div>
				<div class="control-group form-group">
					<div class="controls col-md-6 first">
						<%= f.collection_select :country_id, Country.all, :id, :name, {prompt: "Zgjidh Vendin*"}, {class: "form-control", :required => true} %>
					</div>
					<div class="controls col-md-6">
						<%= f.select :location, [], {prompt: "Zgjidh locacionin*"}, { class: "form-control", require: true } %>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="control-group form-group">
					<div class="controls">
						<%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Zgjidh kategorine e librave*"}, {class: "form-control", :required => true}%>
						<p class="help-block"></p>
					</div>
				</div>
				<div class="control-group form-group">
					<div class="controls col-md-6 first">
						<%= f.text_field :address, placeholder: "Adresa*", class: 'form-control', required: true %>
					</div>
					<div class="controls col-md-6">
						<%= f.text_field :phone, placeholder: "Telefoni*", class: 'form-control', required: true %>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="control-group form-group">
					<div class="controls col-md-6 first">
						<%= f.text_field :title, placeholder: "Titulli i shpalljes*", class: 'form-control', required: true %>
					</div>
					<div class="controls col-md-6">
				    <% if $form_status == "give" %>
							<%= f.text_field :price, class: 'form-control', placeholder: "Cmimi*", :disabled => true %>
						<% elsif $form_status == "sale"  %>
							<%= f.text_field :price, class: 'form-control', placeholder: "Cmimi*", required: true %>
						<% end %>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="control-group form-group">
					<div class="controls">
						<%= f.text_area :description, placeholder: "Permbajtja*", class: 'form-control', style: "resize:none",required: true %>
					</div>
				</div>
				
				<%= f.submit :Vazhdo, class: "form-control text-center", style: "background: #ef7351;font-size:14px;    text-transform: uppercase;color: white" %>
				<% end %>
				
				
			</div>
		</div>
	</div>
</div>




<script>
	var cities = [
		{"country_id": 1, "city": "Artanë"},
		{"country_id": 1, "city": "Besianë"},
		{"country_id": 1, "city": "Burim"},
		{"country_id": 1, "city": "Dardanë"},
		{"country_id": 1, "city": "Deçan"},
		{"country_id": 1, "city": "Dragash"},
		{"country_id": 1, "city": "Drenas"},
		{"country_id": 1, "city": "Ferizaj"},
		{"country_id": 1, "city": "Fushë Kosovë"},
		{"country_id": 1, "city": "Gjakovë"},
		{"country_id": 1, "city": "Gjilan"},
		{"country_id": 1, "city": "Kastriot"},
		{"country_id": 1, "city": "Kaçanik"},
		{"country_id": 1, "city": "Klinë"},
		{"country_id": 1, "city": "Leposaviq"},
		{"country_id": 1, "city": "Lipjan"},
		{"country_id": 1, "city": "Malishevë"},
		{"country_id": 1, "city": "Mitrovicë"},
		{"country_id": 1, "city": "Pejë"},
		{"country_id": 1, "city": "Prishtinë"},
		{"country_id": 1, "city": "Prizren"},
		{"country_id": 1, "city": "Rahovec"},
		{"country_id": 1, "city": "Skenderaj"},
		{"country_id": 1, "city": "Shtërpcë"},
		{"country_id": 1, "city": "Shtime"},
		{"country_id": 1, "city": "Therandë"},
		{"country_id": 1, "city": "Viti"},
		{"country_id": 1, "city": "Vushtrri"},
		{"country_id": 1, "city": "Zubin"},
		{"country_id": 1, "city": "Potok"},
		{"country_id": 1, "city": "Zveçan"},
		{"country_id": 2, "city": "Tirana"},
		{"country_id": 2, "city": "Durrësi"},
		{"country_id": 2, "city": "Elbasani"},
		{"country_id": 2, "city": "Vlora"},
		{"country_id": 2, "city": "Shkodra"},
		{"country_id": 2, "city": "Korça"},
		{"country_id": 2, "city": "Fieri"},
		{"country_id": 2, "city": "Berati"},
		{"country_id": 2, "city": "Lushnja"},
		{"country_id": 2, "city": "Kavaja"},
		{"country_id": 2, "city": "Laçi"},
		{"country_id": 2, "city": "Lezha"},
		{"country_id": 2, "city": "Kukësi"},
		{"country_id": 2, "city": "Gjirokastra"},
		{"country_id": 2, "city": "Kruja"},
		{"country_id": 2, "city": "Saranda"},
		{"country_id": 2, "city": "Librazhdi"},
		{"country_id": 2, "city": "Përmeti"},
		{"country_id": 2, "city": "Peqini"},
		{"country_id": 2, "city": "Puka"},
		{"country_id": 2, "city": "Shëngjini"},
	];
	$('#item_country_id').change(function() {
		var id=$(this).val();
		// var dataString = 'id='+ id;

		var option = '<option selected="selected" value=""> Zgjedh Qytetin* </option>';
		for(var i = 0; i < cities.length; i++) {
			if(cities[i].country_id == id) {
				option += '<option value="'+ cities[i].city+'">'+cities[i].city+'</option>';
			}
		}
		$("#item_location").prop("required", "required");
		$("#item_location").html(option);
	});
</script>

app/views/items/uploads.html.erb
<div class="container">
  <div class="row" style="margin-top: 25px;">
    <div class="titl_sec">
        <div class="col-xs-6">
          <h3 class="main_titl text-left" style="border-bottom: none;margin-right: 20px;">        
          Regjistro Librat      
        </h3>
        <h3 class="main_titl text-left" style="border-bottom: none;width: 30px;">          
           <i class="fa fa-arrow-right" aria-hidden="true"></i>
        </h3>
        <h3 class="main_titl text-left">  
           Galeria e fotografive     
         </h3>
        </div>
        <div class="col-xs-6">
          </h3>
        </div>
        <div class="clearfix"></div>
      </div>
    <div class="col-lg-10 col-lg-offset-1">
      <div class="well">
       <%= form_tag "/delete_image", method: :delete do %>             
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus" aria-hidden="true"></i> Shto fotografi</button>
         <%= submit_tag 'Fshij te perzgjedhurat', id: 'delete', class: 'btn btn-danger pull-right', disabled: @image_content.empty? %>
        <hr>
        <div class="row">
          <div class="col-lg-12">
              <div class="row">
                <div id="media-contents" class="col-lg-12">
                  <% if @image_content.empty? %>
                  <h5 id="no-media">
                    <div class="alert alert-danger">
                      <strong>!</strong> Nuk keni asnje fotografi
                    </div>
                  </h5>
                  <% else %>
                    <% @image_content.each do |media| %>
                      <div class="col-lg-4">
                        <div class="thumbnail">
                          <%= image_tag media.avatar.url(:profile) %>
                          <%= hidden_field_tag :item_id, params[:id] %>
                          <div class="caption">
                            <p>
                              <%= check_box_tag 'image_content[]', media.id %> përzgjedh
                            </p>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <!-- <div class="col-lg-1">
            <%# link_to 'Fshij te gjitha', delete_all_path, method: :get, id: 'delete-all', class: 'btn btn-danger', disabled: @image_content.empty? %>
          </div> -->
        </div>
      </div>

      <div class="well">
       <%= form_tag complete_register_path, method: :get do %> 
        <%= submit_tag 'Perfundo', id: 'finish', class: 'btn pull-right', disabled: @image_content.empty?, style: "background-color:#ef7351;color:white;width: 200px;" %>
        <div class="row">
          <div class="col-lg-12">  
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Shto foto</h4>
      </div>
      <div class="modal-body">
        <%= form_tag '/upload_image', method: :post, class: 'dropzone form', id: 'media-dropzone' do %>
          <div class="fallback">
            <%= file_field 'media', multiple: true %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<br><br><br><br><br>
<br><br><br><br><br>