config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homepages#index'

  resources :items, only: [:new, :create]
  get 'items/uploads', to: "items#uploads"
  get 'items/uploads', to: "items#uploads"
  get 'items/choose_form', to: "items#choose_form"
  get 'items/give_books', to: "items#give_books"
  get 'items/sell_books', to: "items#sell_books"
  post 'upload_image', to: "items#upload_image"  
  delete 'delete_image', to: "items#delete_image"
  get 'complete_register', to: "items#complete_register"

  resources :ks_platform, only: [:index, :show]
  resources :al_platform, only: [:index, :show]
  get "ks_platform_category", to: "ks_platform#category"
  get "al_platform_category", to: "al_platform#category"
  
  get "intrudaction", to: "items#intrudaction"
  get "ks_platform_search", to: "ks_platform#search"
  get "al_platform_search", to: "al_platform#search"
  
  get "contact", to: "contact#index"

end

app/views/layouts/_fouter.html.erb
<footer style="margin: 50px 0px 0px 0px;" id="footer" class="footer">
    <!-- Copyright -->
    <div class="footer_copy_right">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 text-left">
                    <p>&copy;2016. Te gjitha te drejtat jane te rezervuara nga <a href="#"> Mozaix </a>
                    </p>
                </div>
                <div class="col-sm-6 text-right">
                    <p><a href="http://themeforest.net/user/crelegant"> Mozaix Team </a> </p>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<section class="top_sec">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 top_lft">
        <div class="soc_ico">
          <ul>
            <li class="tweet">
              <a href="https://twitter.com/mozaixllc">
                <i class="fa fa-twitter"></i>
              </a>
            </li>
            <li class="fb">
              <a href="https://web.facebook.com/mozaixllc">
                <i class="fa fa-facebook"></i>
              </a>
            </li>
            <li class="linkd">
              <a href="https://www.linkedin.com/company/10234357?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A10234357%2Cidx%3A2-1-2%2CtarId%3A1473546006101%2Ctas%3Amozaix">
                <i class="fa fa-linkedin"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="inf_txt">
          <% if params["controller"] == "ks_platform" %>
          <p>Kosovë</p>
          <% elsif params["controller"] == "al_platform" %>
          <p>Shqipëri</p>
          <% end %>
        </div>
      </div>
      <!-- /.top-left -->
      <div class="col-xs-12 col-md-6 top_rgt">
        <div class="sig_in"></div>
        <div class="submit_prop">
          <h3 class="subm_btn">
          <%= link_to items_choose_form_path do %>
          <i class="fa fa-bars"></i>
          <span> POSTO NJË SHPALLJE </span>
          <% end %>
          </h3>
        </div>
      </div>
      <!-- /.top-right -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>
<!-- Navigation -->
<nav class="navbar" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <!-- Logo -->
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag "logobook.png", width: "150px", height: "50px" %>
      </a>
    </div>
    <!-- Navigation -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">   
      <% if params["controller"] == "ks_platform" %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Kryefaqja", ks_platform_index_path %>
        </li>
        <li>
          <a href="#feat_propty">librat</a>
        </li>
        <li>
          <%= link_to "KATEGORITË", ks_platform_category_path(cat: Item.first.category.name) %>
        </li>
        <li>
          <%= link_to "Kontakti", contact_path %>
        </li>
      </ul>
      <% end %>
      <% if params["controller"] == "al_platform" %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Kryefaqja", al_platform_index_path %>
        </li>
        <li>
          <a href="#feat_propty">librat</a>
        </li>
        <li>
          <%= link_to "KATEGORITË", al_platform_category_path(cat: Item.first.category.name) %>
        </li>
        <li>
          <%= link_to "Kontakti", contact_path %>
        </li>
      </ul>
      <% end %>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'jquery', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>


  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag    'modern-business', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag    'jquery.bxslider.css', media: 'all', 'data-turbolinks-track' => false %>
  
  <!-- Bootstrap Core CSS -->
  <%= stylesheet_link_tag  'owl.carousel', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag  'owl.theme', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag  'owl.transitions', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag  'flexslider', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag  'main_style', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag  'font-awesome.min', media: 'all', 'data-turbolinks-track' => false %>


  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body style="padding: 0px"> 
<% unless params["controller"] == "homepages" %>
  <%= render 'layouts/header' %>
<% end %>

<%= yield %>

<% unless params["controller"] == "homepages" %>
  <%= render 'layouts/fouter' %>
<% end %>


<%= javascript_include_tag 'owl.carousel.min', 'data-turbolinks-track' => false %>
<%= javascript_include_tag 'jquery.flexslider-min', 'data-turbolinks-track' => false %>
<%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => false %>
<%= javascript_include_tag 'jquery.bxslider.min.js', 'data-turbolinks-track' => false %>


<script>
  $('.carousel').carousel({
  	interval: 5000 //changes the speed
	})

    $(document).ready(function () {
        'use strict';
            
        $('#prop_slid').bxSlider({
            pagerCustom: '#slid_nav'
        });
    });
</script>

</body>
</html>